### ISSUE TITLE
I just can't get files listed

### ISSUE THREAD

**Issue by ricbermo** [prscX/react-native-file-selector#16]
Hello there, how you doing?

I managed to get this package running on my RN app but unfortunately I can't get a single file listed, I'm using the default snippet:
```javascript
RNFileSelector.Show({
  title: 'Select File',
  onDone: path => {
    alert(path);
  },
  onCancel: () => null,
});
```
Once I press the button, I get to this screen:
![img_0051](https://user-images.githubusercontent.com/2601363/46702223-e7b3bc00-cbe7-11e8-87b0-1cc124b82ce6.PNG)

I'm not an iOS user so I don't know how to create a file under documents either :D

**Comment by prscX** [comment]
Thanks @ricbermo for raising the query.

You can use [RNFS](https://github.com/itinance/react-native-fs) in order to create/write/read in platform storage.

Once you have files in storage the library will start displaying the same.

Thanks
</ Pranav >
