### ISSUE TITLE
Error while generating the main dex list

### ISSUE THREAD

**Issue by shubham-srivastava-goku** [prscX/react-native-file-selector#18]
I was not able to install at first after installing and linking the library. Then I added below maven dependency.
 
	maven {
		url  "http://dl.bintray.com/lukaville/maven" 
	}

Now it is showing below Error:

	Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
	> com.android.build.api.transform.TransformException: Error while generating the
	 main dex list.

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug
	option to get more log output. Run with --scan to get full insights.

	* Get more help at https://help.gradle.org

	BUILD FAILED in 43s
	421 actionable tasks: 399 executed, 22 up-to-date
	Could not install the app on the device, read the error above for details.
	Make sure you have an Android emulator running or a device connected and have
	set up your Android development environment:
	https://facebook.github.io/react-native/docs/getting-started.html

I have also enabled `multiDexEnabled true` in build.gradle but still stuck at same error. Please help me installing it.

Thanks in advance.

**Comment by haiquan33** [comment]
you should delete the repositories {
    maven {
        url "http://dl.bintray.com/lukaville/maven"
    }
}
 in your Project level gradle.build, and add it to app level gradle.build
