### ISSUE TITLE
Return path?

### ISSUE THREAD

**Issue by mghifariy** [prscX/react-native-file-selector#2]
Nice package btw, but is this package only return path of selected file?
How to return string value if I select text file?

**Comment by prscX** [comment]
Thanks @mghifariy for raising the query.

Signature of API is it returns file path. You can use RNFS in order the fetch the file contents by providing file path.

Thanks
</ Pranav >

**Comment by mghifariy** [comment]
You better add some screenshot and example project. I have tried using RNFS but it same as this package, so I use RNFB file stream and it works very well ^^

**Comment by prscX** [comment]
Thanks @mghifariy for the valuable suggestion. 

We have a example project for the evaluation. Please feel free to raise PR in case you feel something can be improved. I will also work on your suggestions.

Thanks
</ Pranav >
