### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by vieiralucas** [prscX/react-native-file-selector#20]
Can you make a release to npm? I need the fix from #19 and don't want to point my `package.json` to master.
Thanks

**Comment by prscX** [comment]
Sure @vieiralucas. Today I am planning to push the release. Will keep you posted.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @vieiralucas: I have pushed the release. Can you please install latest version and verify the same. Please let me know in case you face any issues.

Thanks
</ Pranav >
