### ISSUE TITLE
Could not find auto-linked framework 'FileBrowser'

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [prscX/react-native-file-selector#26]
Hello. The error is shown when I try to build the project in xCode. What can be the issue?

    ld: warning: Could not find auto-linked framework 'FileBrowser'
    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$__TtC11FileBrowser11FileBrowser", referenced from:
      objc-class-ref in libRNFileSelector.a(RNFileSelector.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by suwu150** [comment]
Have you solved it?

**Comment by VishnuMRI** [comment]
Hi,I am new to IOS.I was working on android using this.Everything was working well there.Now when I am trying to take IOS build,I am getting this same error.How to solve this?Please help.
