### ISSUE TITLE
The following error occurred while running the iOS project

### ISSUE THREAD

**Issue by misscaomin** [prscX/react-native-file-selector#27]
node_modules/react-native-file-selector/ios/Pods/Target Support Files/Pods-RNFileSelector/Pods-RNFileSelector.debug.xcconfig: unable to open file (in target "RNFileSelector" in project "RNFileSelector") (in target 'RNFileSelector')

**Comment by ricbermo** [comment]
hey @misscaomin did u find the solution? I'm facing this right now? thanks

**Comment by whowrongswhere** [comment]
hey @misscaomin did u find the solution? I'm facing this right now? can you share the solution?
