### ISSUE TITLE
 Showing Recent Issues Ad Hoc code signing is not allowed with SDK 'iOS 11.2'

### ISSUE THREAD

**Issue by ailehui** [prscX/react-native-file-selector#3]
![image](https://user-images.githubusercontent.com/23350233/39558942-3cd07156-4ec5-11e8-856c-a78adc7f1983.png)
I didn't know how to solve this problem when I was packing. The project is successfully packaged before using this component

**Comment by prscX** [comment]
Thanks @ailehui for raising the issue. I have encountered the same issue while packaging the app for production.

I am able to resolve this issue using below steps:
- Removed `Bundle Identifier` from `FileBrowser` project.
- Assigned `Team` & `Signing Certificate` in `FileBrowser` project.

Please let me know in case you still face the same issue.

<img width="761" alt="screen shot 2018-05-28 at 11 46 11 am" src="https://user-images.githubusercontent.com/28862892/40599887-ea02eb0a-626c-11e8-9581-1e501530e9c3.png">
<img width="276" alt="screen shot 2018-05-28 at 11 46 21 am" src="https://user-images.githubusercontent.com/28862892/40599894-eea5c18c-626c-11e8-8795-febda8f8d15a.png">


Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @ailehui, I hope the issue was resolved for you. If yes can you please close the raised issue.

Thanks
</ Pranav >
