### ISSUE TITLE
没有找到 "Build Settings -> Frameworks Search Path"

### ISSUE THREAD

**Issue by liaokaime** [prscX/react-native-file-selector#50]
```
Go to your project's Build Settings -> Frameworks Search Path and add ${BUILT_PRODUCTS_DIR}/FileBrowser non-recursive.
```
当我进行到这个步骤时，我在自己的项目下点击Build Settings卡片，但我没有找到`Frameworks Search Path`这项，所以无法再进行下去
![图片](https://user-images.githubusercontent.com/27792976/62029491-40a31e00-b215-11e9-8306-e60a13eb48a9.png)

**Comment by ThreeYearOld** [comment]
找这个 Framework Search Path
