### ISSUE TITLE
 App crash with RN 0.61.x. (Android)

### ISSUE THREAD

**Issue by carl0804** [prscX/react-native-file-selector#68]
App crashed where open file selector. RN version is 0.61.5. Platform is Android

```
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-file-selector": "^1.0.0"
  },
```

```
import React, {Component} from 'react';
import {Text, View, TouchableOpacity} from 'react-native';
import RNFileSelector from 'react-native-file-selector';
export class App extends Component {
  openFile = () => {
    RNFileSelector.Show({
      title: 'Select File',
      onDone: path => {
        console.log('file selected: ' + path);
      },
      onCancel: () => {
        console.log('cancelled');
      },
    });
  };

  render() {
    return (
      <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
        <TouchableOpacity onPress={this.openFile}>
          <Text> open file selector </Text>
        </TouchableOpacity>
      </View>
    );
  }
}

export default App;

```

**Comment by prscX** [comment]
@carl0804: Could you please share the crash logs, you can use flipper also have you added color properties as per defined in README?

Thanks
</ Pranav >

**Comment by iremlaya** [comment]
same issue

**Comment by iremlaya** [comment]
Alright I solved it after checking the examples. It was as you said, about `color.xml`. 
It has to be in `.../res/values` and the complete code is:
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="colorPrimary">#3F51B5</color>
    <color name="colorPrimaryDark">#303F9F</color>
    <color name="colorAccent">#FF4081</color>
</resources>
```

However, as I'm not well versed in android, going of just from your explanation in the installation part mislead me. Had you not added example codes in whole, I'd still be wandering aimlessly. I kindly ask you to be precise with the statements in the documentation. I am opening a PR regarding this as well: [#69](https://github.com/prscX/react-native-file-selector/pull/69) @prscX

**Comment by WynnLu** [comment]
I covered up the same problem. I add the color.xml but it doesn't work. Once I call the  `RNFileSelector.Show()` my app crashes. How to solve it???
