### ISSUE TITLE
Can't find com/nbsp/library/1.8

### ISSUE THREAD

**Issue by zcrkey** [prscX/react-native-file-selector#77]
Can't find com/nbsp/library/1.8

No access https://dl.bintray.com/lukaville/maven

file:/C:/Users/admin/.m2/repository/com/nbsp/library/1.8/library-1.8.pom
file:/C:/Users/admin/.m2/repository/com/nbsp/library/1.8/library-1.8..aar
……

Hope to provide solutions as soon as possible.Or upgrade the react native file selector package

**Comment by tejprakashtiwary** [comment]
Did yoy get any solution? @zcrkey

**Comment by YangShaoXiong** [comment]
+1

**Comment by tejprakashtiwary** [comment]
I find a fix for this
just remove
compile 'com.nbsp:library:1.8'
from build.gradle file from node_modules/react-native-file-selector/android
and add this line
implementation 'com.nbsp:materialfilepicker:1.9.1'

now build, you will not find any error.

**Comment by Tsitsing** [comment]
> I find a fix for this
> just remove
> compile 'com.nbsp:library:1.8'
> from build.gradle file from node_modules/react-native-file-selector/android
> and add this line
> implementation 'com.nbsp:materialfilepicker:1.9.1'
> 
> now build, you will not find any error.

Thanks a lot
