### ISSUE TITLE
when I install this lib and link this, I can not open my app

### ISSUE THREAD

**Issue by crastyle** [prscX/react-native-file-selector#9]
I got an error 

dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/apple/Library/Developer/Xcode/DerivedData/SaletApp-btvptihtfeciokdhrsxvmygljebg/Build/Products/Debug-iphonesimulator/FileBrowser.framework/FileBrowser
  Reason: image not found
(lldb) 

please help me how to resolve my issue,  thank u

**Comment by prscX** [comment]
Thanks @crastyle for raising the issue.

My Bad. I have updated `iOS` installation steps. Can you please install latest version and follow installation steps defined in `README`.

Please let me know incase you face any issues.

Thanks
</ Pranav >
